version: '3'
services:
  frontend:
    build:
      context: ./front-React
      dockerfile: Dockerfile
    ports:
      - 3000:3000


  backend:
    build:
      context: ./backend-Flask
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=crm_prod
      - DB_USER=aristide
      - DB_PASSWORD=aristide


  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=crm_prod
      - POSTGRES_USER=aristide
      - POSTGRES_PASSWORD=aristide